### ISSUE TITLE
Crash app when crop

### ISSUE THREAD

**Issue by nguyenxuankiet262** [howljs/hl_image_picker#14]
i got this error when call openCropper function

E/AndroidRuntime(12767): Caused by: java.lang.ClassNotFoundException: Didn't find class "com.yalantis.ucrop.UCrop" on path: DexPathList[[zip file "/data/app/~~m15gwzKv0ZpxSzU9fBezuw==/com.joongyong.theblack-iaeWzsOVcWf8HmXkpDR6YA==/base.apk"],nativeLibraryDirectories=[/data/app/~~m15gwzKv0ZpxSzU9fBezuw==/com.joongyong.theblack-iaeWzsOVcWf8HmXkpDR6YA==/lib/arm64, /data/app/~~m15gwzKv0ZpxSzU9fBezuw==/com.joongyong.theblack-iaeWzsOVcWf8HmXkpDR6YA==/base.apk!/lib/arm64-v8a, /system/lib64, /system/system_ext/lib64]]
E/AndroidRuntime(12767): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:218)
E/AndroidRuntime(12767): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
E/AndroidRuntime(12767): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
E/AndroidRuntime(12767): 	... 14 more

My code:
 await _picker.openCropper(
            media.path,
            cropOptions: HLCropOptions(
                   aspectRatioPresets: [CropAspectRatioPreset.original, CropAspectRatioPreset.square],
                    compressQuality: 1,
                    compressFormat: CompressFormat.jpg,
                    croppingStyle: CroppingStyle.normal,
                  ),
          )

**Comment by howljs** [comment]
@nguyenxuankiet262 I think there is some special reason, I can't reproduce it like the error you're encountering. Please give me more information so I can reproduce this error

**Comment by nguyenxuankiet262** [comment]
I used another image picker using PictureSelector. I removed it and hl_image_picker works well
