### ISSUE TITLE
openPicker not display downloaded images in device

### ISSUE THREAD

**Issue by nguyenxuankiet262** [howljs/hl_image_picker#16]
I'm using iphone 11 promax, os 17.2.1, xcode 15.1, Flutter SDK 3.13.7

In recent folder, there is missing downloaded images and videos. If i move them to another album in device, openPicker will display them.

**Comment by howljs** [comment]
How to reproduce your issue?

https://github.com/howljs/hl_image_picker/assets/33460888/f97ae8fc-d5bf-4ba9-b5fd-afd38375cea4

**Comment by nguyenxuankiet262** [comment]
> How to reproduce your issue?
> 
>  Simulator.Screen.Recording.-.iPhone.15.Pro.Max.-.2023-12-21.at.23.05.13.mp4

Just download video from telegram, the video exists in Recent album but when openPicker function not show that video

**Comment by nguyenxuankiet262** [comment]
Btw in my Video album, there are 210 videos but library just display about 190 videos
