### ISSUE TITLE
Android device cannot add pictures.

### ISSUE THREAD

**Issue by no-chili** [howljs/hl_image_picker#29]
//log
```
E/OpenGLRenderer( 6761): Unable to match the desired swap behavior.
W/WindowOnBackDispatcher( 6761): sendCancelIfRunning: isInProgress=falsecallback=android.view.ViewRootImpl$$ExternalSyntheticLambda17@a1a7032
```
//env
```
[✓] Flutter (Channel stable, 3.19.6, on macOS 13.6 22G120 darwin-arm64, locale zh-Hans-CN)
[!] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.
[✓] Xcode - develop for iOS and macOS (Xcode 15.0)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.3)
[✓] VS Code (version 1.88.0)
[✓] Connected device (4 available)            
[✓] Network resources

! Doctor found issues in 1 category.
```

**Comment by howljs** [comment]
> //log
> 
> ```
> E/OpenGLRenderer( 6761): Unable to match the desired swap behavior.
> W/WindowOnBackDispatcher( 6761): sendCancelIfRunning: isInProgress=falsecallback=android.view.ViewRootImpl$$ExternalSyntheticLambda17@a1a7032
> ```
> 
> //env
> 
> ```
> [✓] Flutter (Channel stable, 3.19.6, on macOS 13.6 22G120 darwin-arm64, locale zh-Hans-CN)
> [!] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
>     ✗ cmdline-tools component is missing
>       Run `path/to/sdkmanager --install "cmdline-tools;latest"`
>       See https://developer.android.com/studio/command-line for more details.
>     ✗ Android license status unknown.
>       Run `flutter doctor --android-licenses` to accept the SDK licenses.
>       See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.
> [✓] Xcode - develop for iOS and macOS (Xcode 15.0)
> [✓] Chrome - develop for the web
> [✓] Android Studio (version 2022.3)
> [✓] VS Code (version 1.88.0)
> [✓] Connected device (4 available)            
> [✓] Network resources
> 
> ! Doctor found issues in 1 category.
> ```

What is your Android version?

**Comment by no-chili** [comment]
minSdkVersion 21

**Comment by no-chili** [comment]
I apologize, but the reason for the inability to add is due to my incorrect renaming of the file, and there is no issue with the plugin.
