### ISSUE TITLE
can't interact with the screen when onPress backHandler

### ISSUE THREAD

**Issue by MrTuyennn** [howljs/hl_image_picker#31]
when click openCamare -> show popup check permission -> onPress backHandler cancel  ->  show popup permission denied -> close popup -> show error PlatformException(CANCELED, User has canceled the picker, null, null) and I can't interact with the screen because there's a layer over it

**Comment by howljs** [comment]
Please upgrade to v1.2.15

**Comment by nashihu** [comment]
hi, I'm getting the same error from my user. 

they said they can't click OK button after they previously input 2 photos

any guess? i can't reproduce with my device though. it's from Galaxy A20S

in crashlytics the exception is `PlatformException(CANCELED, User has canceled the picker, null, null)`

i'm using v1.2.16

<details close>
<summary>here the screenshot</summary>
<br>

![WhatsApp Image 2025-01-07 at 09 32 15](https://github.com/user-attachments/assets/55e93d60-9cc3-4c30-b913-6dedcbec4206)

![WhatsApp Image 2025-01-07 at 09 32 03](https://github.com/user-attachments/assets/95e21f80-9e63-4737-88eb-3fc03ea885f8)

</details>

thankyou..
