### ISSUE TITLE
Does not support to pick GIF from gallery

### ISSUE THREAD

**Issue by devsideal** [howljs/hl_image_picker#4]
Can we pick media type GIF from gallery eg  `MediaType.gif`  ?

**Comment by howljs** [comment]
You can enable gif now. 
Use isGif in [HLPickerOptions](https://github.com/howljs/hl_image_picker#hlpickeroptions)
<img width="908" alt="Screenshot 2023-10-30 at 17 40 50" src="https://github.com/howljs/hl_image_picker/assets/33460888/28181bca-7dc8-4cbf-bd98-7e77f5297827">

iOS Only:

<img width="892" alt="Screenshot 2023-10-30 at 17 41 03" src="https://github.com/howljs/hl_image_picker/assets/33460888/a4042644-b8c1-4be8-a258-df8cdd59da3d">
